apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-devops-001-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geo-devops-001
  template:
    metadata:
      labels:
        app: geo-devops-001
    spec:
      containers:
      - name: geo-devops-001
        image: 740955001227.dkr.ecr.us-east-1.amazonaws.com/geo-devops-001@sha256:5d65e1e63b59b9c7d62205f37407a554ef167cae273062c5acaa5e89ab78204e
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: geo-devops-001
    k8s-app: geo-devops-001
  name: geo-devops-001
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: geo-devops-001